piVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: no-factor-auth
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: no-factor-auth
      src: .
      ports:
       - name: http
         port: 8089
      public: true
      environmentConfig:
        - environment: production
          variables:
            AUTH_SERVER: "https://no-factor-auth-no-factor-auth-production.playground-4.playground.radix.equinor.com"
            TENANT_ID: "common"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
  dnsAppAlias:
    environment: production
    component: no-factor-auth
